export default {
  id: 'backatorpif',
  name: 'Backatorp IF Portal',
  baseURL: process.env.BIF_BASE_URL || 'https://portal.backatorpif.se',

  auth: {
    loginPath: '/login',
    logoutSelector: 'button.btn-logout',
    postLoginPattern: /\/admin/,
    loginRedirectPattern: /\/login/,

    credentials: {
      username: process.env.BIF_ADMIN_USERNAME || process.env.ADMIN_USERNAME || 'admin',
      password: process.env.BIF_ADMIN_PASSWORD || process.env.ADMIN_PASSWORD || '',
    },

    selectors: {
      username: 'input[name="username"]',
      password: 'input[name="password"]',
      association: 'select[name="association_id"]',
      csrf: 'input[name="csrf_token"]',
      submit: 'button.btn-primary[type="submit"]',
    },

    extraFields: [
      { selector: 'select[name="association_id"]', action: 'select', value: '1' },
    ],
  },

  routes: {
    'Översikt & Inställningar': [
      '/admin/settings',
      '/admin/permissions',
      '/admin/roadmap',
      '/admin/reports',
      '/admin/reports/sms',
      '/admin/reports/email',
      '/admin/reports/invitations',
      '/admin/reports/logs',
      '/admin/reports/cron',
      '/admin/backup',
    ],
    'Medlemmar & Användare': [
      '/admin/members',
      '/admin/admin-users',
      '/admin/associations',
      '/admin/teams',
      '/admin/group-invites',
    ],
    'API & Cron': [
      '/admin/api',
      '/admin/api/docs',
      '/admin/api/users',
      '/admin/api/users/create',
      '/admin/cron',
      '/admin/cron/history',
      '/admin/action-types',
      '/admin/action-types/create',
    ],
    'Kommunikation': [
      '/admin/sms',
      '/admin/sms/settings',
      '/admin/email/settings',
      '/admin/messages',
      '/admin/messages/create',
    ],
    'Kalender & Events': [
      '/admin/calendar',
      '/admin/calendar/events',
      '/admin/calendar/mapping',
      '/admin/calendar/settings',
      '/admin/events',
      '/admin/events/create',
    ],
    'Närvaro & Poäng': [
      '/admin/attendance',
      '/admin/attendance/report',
      '/admin/attendance/settings',
      '/admin/points',
      '/admin/points/leaderboard',
      '/admin/points/settings',
    ],
    'Uppgifter & Journeys': [
      '/admin/tasks',
      '/admin/tasks/templates',
      '/admin/tasks/templates/create',
      '/admin/tasks/pending',
      '/admin/tasks/categories',
      '/admin/tasks/manual/create',
      '/admin/journeys',
      '/admin/journeys/create',
    ],
    'Dokument': [
      '/admin/dok',
      '/admin/dok/create',
      '/admin/dok/categories',
      '/admin/dok/pending',
      '/admin/dok/stats',
    ],
    'Integrationer': [
      '/admin/integrations',
      '/admin/integrations/parakey',
      '/admin/integrations/parakey/logs',
      '/admin/fogis',
      '/admin/fogis/club',
      '/admin/fogis/teams',
      '/admin/fogis/persons',
      '/admin/fogis/competitions',
      '/admin/fogis/imports',
      '/admin/fogis/games',
      '/admin/fogis/standings',
      '/admin/fogis/link-teams',
      '/admin/fogis/change-log',
      '/admin/fogis/clubs',
      '/admin/fogis/clubs/import-contacts',
      '/admin/laget',
      '/admin/parakey',
      '/admin/parakey/members',
      '/admin/parakey/keys',
      '/admin/parakey/events',
      '/admin/pitchstatus',
      '/admin/pitchstatus/settings',
      '/admin/entities',
      '/admin/entities/list',
      '/admin/entities/settings',
    ],
    'Förening': [
      '/admin/association-roles',
      '/admin/association-roles/types',
      '/admin/association-roles/assign',
      '/admin/association-referees',
      '/admin/association-referees/manage',
    ],
    'Bokningar & Lager': [
      '/admin/inventory',
      '/admin/inventory/categories',
      '/admin/inventory/items',
      '/admin/inventory/items/create',
      '/admin/orders',
      '/admin/orders/pending',
    ],
    'Fakturering': [
      '/admin/invoices',
      '/admin/invoices/create',
      '/admin/invoices/fees',
      '/admin/invoices/fees/create',
      '/admin/invoices/settings',
      '/admin/invoices/batch',
      '/admin/invoices/batch/create',
    ],
    'Forum': [
      '/admin/forum',
      '/admin/forum/groups',
      '/admin/forum/groups/new',
      '/admin/forum/moderation',
      '/admin/forum/reports',
    ],
    'Utbildningar': [
      '/admin/educ',
      '/admin/educ/create',
    ],
    'Ansökningar': [
      '/admin/applications',
      '/admin/applications/list',
      '/admin/applications/waitlist',
      '/admin/applications/settings',
      '/admin/applications/settings/checklists',
    ],
    'Partners': [
      '/admin/partners',
      '/admin/partners/create',
      '/admin/partners/export',
    ],
    'Formulär': [
      '/admin/forms',
      '/admin/forms/create',
      '/admin/forms/library',
    ],
    'Bingo': [
      '/admin/bingo',
      '/admin/bingo/settings',
      '/admin/bingo/export',
    ],
  },

  responsivePages: [
    { path: '/admin/settings', name: 'Inställningar' },
    { path: '/admin/members', name: 'Medlemmar' },
    { path: '/admin/calendar', name: 'Kalender' },
    { path: '/admin/attendance', name: 'Närvaro' },
    { path: '/admin/points', name: 'Poäng' },
    { path: '/admin/invoices', name: 'Fakturering' },
    { path: '/admin/tasks', name: 'Uppgifter' },
    { path: '/admin/fogis', name: 'FOGIS' },
    { path: '/admin/messages', name: 'Meddelanden' },
    { path: '/admin/forum', name: 'Forum' },
  ],

  criticalPages: [
    '/admin/settings',
    '/admin/members',
    '/admin/calendar',
    '/admin/attendance',
    '/admin/points',
    '/admin/invoices',
    '/admin/fogis',
    '/admin/sms',
    '/admin/tasks',
    '/admin/forum',
  ],
};
